---
- name: Setting connection variables
  set_fact:
    input: &connection_vars
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      verifycert: "{{ verifycert }}"
      user: "{{ user }}"
      password:  "{{ password }}"
      serial_no: "{{ serial_no }}"
  no_log: True

# Create empty storage group
- name: Create empty storage group
  dellemc.powermax.dellemc_powermax_storagegroup:
    <<: *connection_vars
    sg_name: "{{ sg_name }}"
    service_level:  "{{ service_level }}"
    srp: "{{ srp }}"
    compression: True
    state: "present"

# Loop to Create volumes in storage group from volume_list input list"
- name: Create volumes
  register: result
  dellemc.powermax.dellemc_powermax_volume:
    <<: *connection_vars
    sg_name: "{{ sg_name }}"
    vol_name: "{{ item.vol_name}}"
    size: "{{ item.size }}"
    cap_unit: "{{ item.cap_unit }}"
    state: "present"
  with_items: "{{ volume_list }}"

# This task will create a host with given host_name and initiators
- name: Create host
  dellemc.powermax.dellemc_powermax_host:
    <<: *connection_vars
    host_name: "{{ host_name }}"
    initiators: "{{ initiators }}"
    state: 'present'
    initiator_state: 'present-in-host'

# This task will create a port group with given portgroup_name and ports
- name: Create port group
  dellemc.powermax.dellemc_powermax_portgroup:
    <<: *connection_vars
    portgroup_name: "{{ portgroup_name }}"
    state: "present"
    ports: "{{ ports }}"
    port_state: "present-in-group"

# This task creates a masking view with given mv_name, portgroup_name, host_name, sg_name. **previous tasks
- name: Create MV with host
  dellemc.powermax.dellemc_powermax_maskingview:
    <<: *connection_vars
    mv_name: "{{ mv_name }}"
    portgroup_name: "{{ portgroup_name }}"
    host_name: "{{ host_name }}"
    sg_name: "{{ sg_name }}"
    state: "present"
