# Variable File containing cluster volume config and storage group details
---
# Main Variable Inputs for Playbook
portgroup_name: Ansible_Cluster_PG
mv_name: Ansible_Cluster_MV
sg_name: Ansible_Cluster_SG

# Ports to be Used

port_list:
  - director_id: FA-1D
    port_id: 8 
  - director_id: FA-2D
    port_id: 8


# Storage Definition
    
volume_list:
  - vol_name: UniDev1
    size: 1
    cap_unit: GB
  - vol_name: UniDev2
    size: 1
    cap_unit: GB
  - vol_name: UniDev3
    size: 1
    cap_unit: GB

