---
- name: Provisioning storage for Powermax
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars_files/connection.yml
    - vars_files/credentials.yml
    - vars_files/cluster_storage_details.yml
    - vars_files/3node_cluster_hosts.yml

  vars:
    mv_name: "{{ mv_name }}"
    portgroup_name: "{{ portgroup_name }}"
    hostgroup_name: "{{ hostgroup_name }}"
    sg_name: "{{ sg_name }}"
    vol_name: "Ansible_vol"

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{  user  }}"
      verifycert: "{{ verifycert }}"

  tasks:
    - name: Create Storage group
      dellemc_powermax_storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ sg_name }}"
        service_level: "Bronze"
        state: 'present'

    - name: Create volumes
      register: result
      dellemc_powermax_volume:
        <<: *uni_connection_vars
        vol_name: "{{vol_name +'_' }}{{item}}"
        sg_name: "{{sg_name}}"
        size: 1
        cap_unit: "GB"
        state: 'present'
      loop: "{{ range(1, 3 + 1, 1) | list }}"

    - name: Create host "{{ host1_name }}"
      dellemc_powermax_host:
        <<: *uni_connection_vars
        host_name: "{{ host1_name }}"
        initiators: "{{ host1_initiators }}"
        state: 'present'
        initiator_state: 'present-in-host'

    - name: Create host "{{ host2_name }}"
      dellemc_powermax_host:
        <<: *uni_connection_vars
        host_name: "{{ host2_name }}"
        initiators: "{{ host2_initiators }}"
        state: 'present'
        initiator_state: 'present-in-host'

    - name: Create host group "{{ hostgroup_name }}"
      dellemc_powermax_hostgroup:
        <<: *uni_connection_vars
        hostgroup_name: "{{ hostgroup_name }}"
        state: "present"
        hosts:
          - "{{ host1_name }}"
          - "{{ host2_name }}"
        host_state: 'present-in-group'

    - name: Remove host from  host group "{{ hostgroup_name }}"
      dellemc_powermax_hostgroup:
        <<: *uni_connection_vars
        hostgroup_name: "{{ hostgroup_name }}"
        state: "present"
        hosts:
          - "{{ host3_name }}"
        host_state: 'absent-in-group'

    - name: Delete host "{{ host3_name }}"
      dellemc_powermax_host:
        <<: *uni_connection_vars
        host_name: "{{ host3_name }}"
        initiators: "{{ host3_initiators }}"
        state: 'absent'
        initiator_state: 'present-in-host'

    - name: Create port group "{{ portgroup_name }}"
      dellemc_powermax_portgroup:
        <<: *uni_connection_vars
        portgroup_name: "{{ portgroup_name }}"
        state: "present"
        ports:  "{{ port_list }}"
        port_state: 'present-in-group'

    - name: Create MV "{{ mv_name }}" with existing elements
      dellemc_powermax_maskingview:
        <<: *uni_connection_vars
        mv_name: "{{ mv_name }}"
        portgroup_name: "{{ portgroup_name }}"
        hostgroup_name: "{{ hostgroup_name }}"
        sg_name: "{{ sg_name }}"
        state: 'present'

